-- Schema for the `pg` end-to-end test suite.
--
-- Anything the tests assert on (database names, table names, column names,
-- index names, row counts) is fixed here. Tests that need to mutate data
-- create their own scratch tables, so re-running the suite against a live
-- container is safe.
--
-- Runs as POSTGRES_USER against POSTGRES_DB (pg_e2e) on first boot.

-- A second database, reachable via the `alt` profile, so profile switching is
-- covered end to end.
CREATE DATABASE pg_e2e_alt;

-- Deliberately left without a single table, so `pg psql tables` is covered
-- against a database where the catalog query returns no rows.
CREATE DATABASE pg_e2e_empty;

\connect pg_e2e

-- A real enum type: `describe-table` reports it as USER-DEFINED, which a
-- CHECK-constrained text column would not exercise.
CREATE TYPE user_status AS ENUM ('active', 'inactive', 'banned');

CREATE TABLE users (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      varchar(255) NOT NULL,
  name       varchar(100) NOT NULL,
  status     user_status NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uniq_users_email ON users (email);
CREATE INDEX idx_users_status ON users (status);

CREATE TABLE orders (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  total      numeric(10, 2) NOT NULL,
  status     varchar(32) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_user_id ON orders (user_id);

-- Big enough that the planner really picks the index, so the EXPLAIN assertion
-- tests something instead of restating itself. No foreign key: user_id here
-- spreads across 50 synthetic users, not the five seeded into `users`.
CREATE TABLE wide_orders (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  amount  numeric(10, 2) NOT NULL
);

CREATE INDEX idx_wide_orders_user_id ON wide_orders (user_id);

-- Deliberately more than the default LIMIT of 100 so the auto-LIMIT behaviour
-- is observable through the CLI.
CREATE TABLE metrics (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label varchar(32) NOT NULL,
  value integer NOT NULL
);

-- Exercises the CSV/TOON formatters' escaping, NULL and binary handling.
CREATE TABLE quirky (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note     text NULL,
  payload  bytea NULL,
  recorded timestamptz NULL
);

\connect pg_e2e_alt

CREATE TABLE audit_log (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action   varchar(64) NOT NULL,
  actor_id integer NOT NULL
);
